version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel-network

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel-network

volumes:
    postgres_data:

networks:
    laravel-network:
        driver: bridge
